# Generated by Django 4.1.3 on 2022-11-28 13:21

from django.db import migrations, models
import django.db.models.deletion
import pictures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandeiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bandeira', models.CharField(choices=[('V', 'Visa'), ('M', 'MasterCard'), ('E', 'Elo'), ('H', 'Hipercard')], default='V', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(max_length=25)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cartao_fisico', models.BooleanField()),
                ('data_vencimento', models.DateField()),
                ('bandeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.bandeiras')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=20)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_emprestimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_parcelas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numero_parcelas', models.PositiveSmallIntegerField()),
                ('aprovado', models.BooleanField()),
                ('pagamento_correto', models.BooleanField()),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('horario_emprestimo', models.TimeField(auto_now_add=True)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.PositiveSmallIntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('foto', pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='home/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('B', 'Basic'), ('G', 'Gold'), ('P', 'Platinum')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=15)),
                ('bloqueio_acesso', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horario_transferencia', models.TimeField(auto_now_add=True)),
                ('data_transferencia', models.DateField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinatario', to='home.cliente')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remetente', to='home.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pgto_Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('cod_emprestimos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.emprestimos')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_fatura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cod_cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cartoes')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_extrato', models.DateField(auto_now_add=True)),
                ('horario_extrato', models.TimeField(auto_now_add=True)),
                ('cod_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conta')),
            ],
        ),
        migrations.AddField(
            model_name='conta',
            name='tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.tipos_cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cod_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.tipos_cliente'),
        ),
        migrations.AddField(
            model_name='cartoes',
            name='cod_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conta'),
        ),
    ]
