# Generated by Django 4.1.1 on 2022-09-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='home/images')),
            ],
        ),
        migrations.RenameField(
            model_name='tipos_cliente',
            old_name='tipo',
            new_name='tipo_cliente',
        ),
        migrations.RemoveField(
            model_name='cartoes',
            name='nome_cliente',
        ),
        migrations.AlterField(
            model_name='cartoes',
            name='cod_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cod_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='cod_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente'),
        ),
        migrations.AlterField(
            model_name='extrato',
            name='cod_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conta'),
        ),
        migrations.AlterField(
            model_name='pgto_emprestimos',
            name='cod_emprestimos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.emprestimos'),
        ),
    ]
