# Generated by Django 4.1.1 on 2022-09-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_imagem_rename_tipo_tipos_cliente_tipo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='foto',
            field=models.ImageField(upload_to='home/imagens'),
        ),
    ]
